-- ========================================
-- CONSULTAR USUÁRIOS DISTRIBUIDORES
-- ========================================

-- 1. LISTAR TODAS AS PESSOAS DO TIPO DISTRIBUIDOR
SELECT
    P.ID as ID_PESSOA,
    P.NOME,
    P.LOGIN,
    P.SENHA,
    P.CPFCNPJ,
    P.TIPO,
    P.SITUACAO
FROM PESSOA P
WHERE P.TIPO = 'DISTRIBUIDOR'
  AND P.SITUACAO_REGISTRO = 'ATIVO';

-- 2. LISTAR DISTRIBUIDORES COM SEUS IDs
SELECT
    D.ID as ID_DISTRIBUIDOR,
    D.ID_PESSOA,
    P.NOME,
    P.LOGIN,
    P.SENHA,
    P.CPFCNPJ,
    P.TIPO
FROM DISTRIBUIDORES D
INNER JOIN PESSOA P ON D.ID_PESSOA = P.ID
WHERE P.SITUACAO_REGISTRO = 'ATIVO';

-- 3. VERIFICAR SE EXISTE ALGUM DISTRIBUIDOR CADASTRADO
SELECT COUNT(*) as TOTAL_DISTRIBUIDORES
FROM PESSOA
WHERE TIPO = 'DISTRIBUIDOR'
  AND SITUACAO_REGISTRO = 'ATIVO';

-- 4. LISTAR TODOS OS TIPOS DE PESSOA DISPONÍVEIS
SELECT DISTINCT TIPO, COUNT(*) as QUANTIDADE
FROM PESSOA
WHERE SITUACAO_REGISTRO = 'ATIVO'
GROUP BY TIPO;
