-- ========================================
-- DEBUG FINAL: Ver definição da VIEW e corrigir
-- ========================================

USE allmoove;
GO

-- 1. Ver definição completa da VIEW
PRINT '📋 DEFINIÇÃO DA VIEW_DISTRIBUIDOR_CONSULTA:';
GO

SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.VIEW_DISTRIBUIDOR_CONSULTA')) AS ViewDefinition;
GO

-- 2. Ver dados da tabela DISTRIBUIDORES
PRINT '';
PRINT '🏪 TABELA DISTRIBUIDORES:';
GO

SELECT * FROM dbo.DISTRIBUIDORES;
GO

-- 3. Ver dados da tabela DISTRIBUIDOR_SEGMENTO
PRINT '';
PRINT '📊 TABELA DISTRIBUIDOR_SEGMENTO:';
GO

SELECT
    DS.ID,
    DS.ID_DISTRIBUIDOR,
    DS.ID_SEGMENTO,
    D.ID_PESSOA,
    P.NOME,
    P.CPFCNPJ
FROM dbo.DISTRIBUIDOR_SEGMENTO DS
INNER JOIN dbo.DISTRIBUIDORES D ON DS.ID_DISTRIBUIDOR = D.ID
INNER JOIN dbo.PESSOA P ON D.ID_PESSOA = P.ID
WHERE DS.ID_DISTRIBUIDOR IN (2, 3, 4)
ORDER BY DS.ID_DISTRIBUIDOR, DS.ID_SEGMENTO;
GO

-- 4. Simulação manual da VIEW (para ver se os dados estão corretos)
PRINT '';
PRINT '🧪 SIMULAÇÃO MANUAL DA VIEW:';
GO

SELECT
    D.ID as ID_DISTRIBUIDOR,
    DS.ID_SEGMENTO,
    P.NOME,
    P.CPFCNPJ
FROM dbo.DISTRIBUIDORES D
INNER JOIN dbo.PESSOA P ON D.ID_PESSOA = P.ID
CROSS JOIN dbo.DISTRIBUIDOR_SEGMENTO DS
WHERE DS.ID_DISTRIBUIDOR = D.ID
  AND P.SITUACAO_REGISTRO = 'ATIVO'
ORDER BY D.ID, DS.ID_SEGMENTO;
GO
