-- ========================================
-- DESCOBRIR ESTRUTURA REAL DA TABELA PRODUTOS
-- ========================================

USE allmoove;
GO

-- 1. Ver todas as colunas da tabela PRODUTOS
PRINT '📋 ESTRUTURA COMPLETA DA TABELA PRODUTOS:';
GO

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTOS'
ORDER BY ORDINAL_POSITION;
GO

-- 2. Ver estrutura da tabela PESSOA_PAPEL
PRINT '';
PRINT '📋 ESTRUTURA DA TABELA PESSOA_PAPEL:';
GO

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PESSOA_PAPEL'
ORDER BY ORDINAL_POSITION;
GO

-- 3. Ver 1 registro de exemplo (para entender os valores)
PRINT '';
PRINT '🔍 EXEMPLO DE PRODUTO:';
GO

SELECT TOP 1 * FROM dbo.PRODUTOS;
GO

-- 4. Ver 1 registro de PESSOA_PAPEL
PRINT '';
PRINT '🔍 EXEMPLO DE PESSOA_PAPEL:';
GO

SELECT TOP 5 * FROM dbo.PESSOA_PAPEL;
GO

-- 5. Verificar se PRODUTOS é uma VIEW ou TABLE
PRINT '';
PRINT '🔍 TIPO DE OBJETO - PRODUTOS:';
GO

SELECT
    TABLE_NAME,
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'PRODUTOS';
GO

-- 6. Se for VIEW, mostrar definição
PRINT '';
PRINT '🔍 DEFINIÇÃO DA VIEW PRODUTOS (se for view):';
GO

SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.PRODUTOS')) AS ViewDefinition;
GO
