-- ========================================
-- EXPORTAR ESTRUTURA COMPLETA DA TABELA PRODUTO
-- ========================================

USE allmoove;
GO

-- 1. Ver estrutura da tabela PRODUTO (tabela base, não VIEW)
PRINT '📋 ESTRUTURA DA TABELA PRODUTO (BASE):';
GO

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTO'
ORDER BY ORDINAL_POSITION;
GO

-- 2. Ver exemplo de dados da tabela PRODUTO
PRINT '';
PRINT '🔍 EXEMPLO DE DADOS DA TABELA PRODUTO:';
GO

SELECT TOP 3 * FROM dbo.PRODUTO WHERE SITUACAO_REGISTRO = 'ATIVO';
GO

-- 3. Ver definição da VIEW PRODUTOS
PRINT '';
PRINT '📋 DEFINIÇÃO DA VIEW PRODUTOS:';
GO

SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.PRODUTOS')) AS ViewDefinition;
GO

-- 4. Comparar colunas: PRODUTO (tabela) vs PRODUTOS (view)
PRINT '';
PRINT '📊 COMPARAÇÃO: Colunas na tabela PRODUTO vs VIEW PRODUTOS:';
GO

SELECT
    'PRODUTO (tabela)' AS Origem,
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTO'
UNION ALL
SELECT
    'PRODUTOS (view)' AS Origem,
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTOS'
ORDER BY Origem, COLUMN_NAME;
GO
